name: fugas

on: [push]

jobs:
  gitleaks:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Gitleaks
      run: |
        Invoke-WebRequest -Uri "https://github.com/zricethezav/gitleaks/releases/download/v7.1.2/gitleaks-windows-amd64.exe" -OutFile gitleaks.exe
        .\gitleaks.exe --verbose
