name: fugas

on:
  push:
    branches:
      - main  # Cambia "main" por el nombre de tu rama principal si es diferente

jobs:
  gitleaks:
    runs-on: windows-latest  # Se ejecutar치 en un entorno Windows
    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v2  # Utiliza la acci칩n "checkout" para clonar el repositorio
     
     - name: Ejecutar Gitleaks
        uses: zricethezav/gitleaks-action@v5  # Utiliza la acci칩n Gitleaks
        with:
          args: --path .  # Especifica la ruta del repositorio a escanear
